run:
  name: "dqn-optuna-phase2-best-resume-30k-steps"
  seed: 7
  output_root: "runs"
  save_replay_frames: false

game:
  repo_path: "D:/rl-dino"
  index_file: "index.html"
  serve:
    host: "127.0.0.1"
    port: 8000
    auto_start: true
  browser:
    headless: true
    slow_mo_ms: 0
    viewport_width: 960
    viewport_height: 540
  env:
    canvas_selector: "#game"
    frame_width: 84
    frame_height: 84
    frame_stack: 4
    grayscale: true
    crop_top: 0
    crop_bottom: 32
    crop_left: 0
    crop_right: 0
    step_ms: 16.6667
    max_episode_steps: 30000
    reward_mode: "clip_survival"
    reward_scale: 1.0
    jump_penalty: 0.025309667634950364
    obstacle_clear_bonus: 0.331522607507297
    unsafe_descent_penalty: 0.02405156938736382
    unsafe_descent_distance: 47.93211318146528

training:
  total_timesteps: 400000
  learning_rate: 0.00016047603182752895
  learning_rate_schedule: "linear"
  learning_rate_end: 0.000011629939087813681
  buffer_size: 50000
  learning_starts: 2000
  batch_size: 32
  gamma: 0.9891830368631348
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 500
  exploration_fraction: 0.12741026988907145
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  stats_window_size: 50
  tensorboard_log_subdir: "tensorboard"
  save_checkpoint_every_steps: 50000
  keep_last_checkpoints: 5
  save_replay_buffer_checkpoints: false
  plot_every_episodes: 20
  model_policy: "CnnPolicy"
  feature_extractor: "medium_dino_cnn"
  features_dim: 256
  q_net_arch: [256, 128]
  device: "auto"
  verbose: 1
  early_stop_patience_episodes: 160
  early_stop_min_episodes: 220
  early_stop_min_timesteps: 120000
  early_stop_window_episodes: 20
  early_stop_metric: "score"
  early_stop_min_delta: 3.0
  demo_every_steps: 0
  demo_episodes: 1
  demo_deterministic: true
  demo_headless: false
  demo_sleep_after_episode: 0.5

evaluation:
  deterministic: true
  episodes: 1
  eval_freq_steps: 0
  headless: true
